dist: xenial

language: node_js

services:
  - xvfb

_aliases:
  - &test
    before_install:
      - sleep 1
  - &unit-test
    env: DISPLAY=:99.0 FIREFOX_BINARY=firefox
    addons:
      firefox: latest
    <<: *test
  - &integration-test
    env: DISPLAY=:99.0 MOZ_HEADLESS=1 UI_TEST_LOGGING=info GECKODRIVER_VERSION=0.21.0
    addons:
      firefox: latest-nightly
    before_script:
      - wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
      - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
      - export PATH=$HOME/geckodriver:$PATH
      - firefox --version
      - geckodriver --version
      - npm run build
    <<: *test

jobs:
  include:
    - stage:
      node_js: 12
      <<: *unit-test
      script: npm run test:karma
    - stage:
      node_js: 8
      script: npm run build
      env: BUILD_NOTES
    - stage:
      node_js: 8
      script: npm run lint
      env: LINT
      before_script: npm run build
      before_install:
